<template>
    <div>
        map3
        <div id="myChart1"></div>
        <div>
        </div>
    </div>
</template>
<script>
    export default {
        mounted() {
            let graph = {
                links: [{
                    "source": 0,
                    "target": 1
                }, {
                    "source": 0,
                    "target": 2
                }, {
                    "source": 0,
                    "target": 3
                }, {
                    "source": 0,
                    "target": 4
                }, {
                    "source": 0,
                    "target": 5
                }, {
                    "source": 0,
                    "target": 6
                }, {
                    "source": 4,
                    "target": 7
                }, {
                    "source": 4,
                    "target": 8
                }, {
                    "source": 4,
                    "target": 9
                }, {
                    "source": 4,
                    "target": 10
                }, {
                    "source": 4,
                    "target": 11
                }, {
                    "source": 4,
                    "target": 12
                }, {
                    "source": 4,
                    "target": 13
                }, {
                    "source": 4,
                    "target": 14
                }, {
                    "source": 4,
                    "target": 15
                }, {
                    "source": 4,
                    "target": 16
                }, {
                    "source": 4,
                    "target": 17
                }, {
                    "source": 4,
                    "target": 18
                }, {
                    "source": 6,
                    "target": 19
                }, {
                    "source": 6,
                    "target": 20
                }, {
                    "source": 6,
                    "target": 21
                }, {
                    "source": 6,
                    "target": 22
                }, {
                    "source": 6,
                    "target": 23
                }, {
                    "source": 6,
                    "target": 24
                }, {
                    "source": 6,
                    "target": 25
                }, {
                    "source": 6,
                    "target": 26
                }, {
                    "source": 6,
                    "target": 27
                }, {
                    "source": 2,
                    "target": 28
                }, {
                    "source": 2,
                    "target": 29
                }, {
                    "source": 2,
                    "target": 30
                }, {
                    "source": 2,
                    "target": 31
                }, {
                    "source": 2,
                    "target": 32
                }, {
                    "source": 2,
                    "target": 33
                }, {
                    "source": 2,
                    "target": 34
                }, {
                    "source": 2,
                    "target": 35
                }, {
                    "source": 2,
                    "target": 36
                }, {
                    "source": 2,
                    "target": 36
                }, {
                    "source": 3,
                    "target": 37
                }, {
                    "source": 3,
                    "target": 38
                }, {
                    "source": 3,
                    "target": 39
                }, {
                    "source": 3,
                    "target": 40
                }, {
                    "source": 3,
                    "target": 41
                }, {
                    "source": 3,
                    "target": 42
                }, {
                    "source": 3,
                    "target": 43
                }, {
                    "source": 3,
                    "target": 44
                }, {
                    "source": 3,
                    "target": 45
                }, {
                    "source": 3,
                    "target": 46
                }, {
                    "source": 3,
                    "target": 47
                }, {
                    "source": 3,
                    "target": 48
                }, {
                    "source": 5,
                    "target": 49
                }, {
                    "source": 5,
                    "target": 50
                }, {
                    "source": 5,
                    "target": 51
                }, {
                    "source": 5,
                    "target": 52
                }, {
                    "source": 5,
                    "target": 53
                }, {
                    "source": 5,
                    "target": 54
                }, {
                    "source": 5,
                    "target": 55
                }, {
                    "source": 5,
                    "target": 56
                }, {
                    "source": 1,
                    "target": 57
                }, {
                    "source": 1,
                    "target": 58
                }, {
                    "source": 1,
                    "target": 59
                }, {
                    "source": 1,
                    "target": 60
                }, {
                    "source": 1,
                    "target": 61
                }, {
                    "source": 1,
                    "target": 62
                }, {
                    "source": 1,
                    "target": 63
                }],
                nodes: [{
                    "name": "新冠肺炎\n预防知识图谱",
                    "symbolSize": 60
                }, {
                    "name": "传染病相关知识",
                    "symbolSize": 20
                }, {
                    "name": "发现与治疗",
                    "symbolSize": 20
                }, {
                    "name": "个人防护措施",
                    "symbolSize": 20
                }, {
                    "name": "冠状病毒",
                    "symbolSize": 20
                }, {
                    "name": "场所卫生要求",
                    "symbolSize": 20
                }, {
                    "name": "传播风险",
                    "symbolSize": 20
                }, {
                    "name": "呼吸道病毒简介",
                    "symbolSize": 10
                }, {
                    "name": "常见的呼吸道病毒",
                    "symbolSize": 10
                }, {
                    "name": "什么是冠状病毒",
                    "symbolSize": 10
                }, {
                    "name": "冠状病毒形态与结构",
                    "symbolSize": 10
                }, {
                    "name": "冠状病毒的分类",
                    "symbolSize": 10
                }, {
                    "name": "会携带冠状病毒\n的野生动物",
                    "symbolSize": 10
                }, {
                    "name": "如何由动物传到人",
                    "symbolSize": 10
                }, {
                    "name": "哪些冠状病毒\n可以引起人类的肺炎",
                    "symbolSize": 10
                }, {
                    "name": "冠状病毒的抵抗力",
                    "symbolSize": 10
                }, {
                    "name": "冠状病毒的致病性",
                    "symbolSize": 10
                }, {
                    "name": "冠状病毒的免疫力",
                    "symbolSize": 10
                }, {
                    "name": "社区获得性肺炎",
                    "symbolSize": 10
                }, {
                    "name": "社区获得性肺炎\n临床诊断标准",
                    "symbolSize": 10
                }, {
                    "name": "常见的社区获得性肺炎\n病原体",
                    "symbolSize": 10
                }, {
                    "name": "社区获得性肺炎\n如何形成人际循环",
                    "symbolSize": 10
                }, {
                    "name": "社区存在\n传播肺炎的危险因素",
                    "symbolSize": 10
                }, {
                    "name": "社区获得性肺炎的预防",
                    "symbolSize": 10
                }, {
                    "name": "如何居家消毒",
                    "symbolSize": 10
                }, {
                    "name": "疫情的流行病学特点",
                    "symbolSize": 10
                }, {
                    "name": "新冠病毒的传播途径",
                    "symbolSize": 10
                }, {
                    "name": "为什么要对密切接触者\n医学观察14天",
                    "symbolSize": 10
                }, {
                    "name": "病人的临床表现",
                    "symbolSize": 10
                }, {
                    "name": "新冠肺炎的实验室检查",
                    "symbolSize": 10
                }, {
                    "name": "病人的胸部影像学特征",
                    "symbolSize": 10
                }, {
                    "name": "临床识别新冠肺炎病例",
                    "symbolSize": 10
                }, {
                    "name": "如何快速检测确定感染",
                    "symbolSize": 10
                }, {
                    "name": "治疗应选择的场所",
                    "symbolSize": 10
                }, {
                    "name": "运送病人的转运原则",
                    "symbolSize": 10
                }, {
                    "name": "新冠肺炎如何治疗",
                    "symbolSize": 10
                }, {
                    "name": "临床解除隔离和出院的标准",
                    "symbolSize": 10
                }, {
                    "name": "新冠肺炎的保护原理",
                    "symbolSize": 10
                }, {
                    "name": "口罩的类型",
                    "symbolSize": 10
                }, {
                    "name": "不同类型口罩的特点",
                    "symbolSize": 10
                }, {
                    "name": "口罩KN95和N95的区别",
                    "symbolSize": 10
                }, {
                    "name": "口罩的正确使用",
                    "symbolSize": 10
                }, {
                    "name": "口罩的使用期限",
                    "symbolSize": 10
                }, {
                    "name": "口罩的选择",
                    "symbolSize": 10
                }, {
                    "name": "洗手在预防疾病传播的作用",
                    "symbolSize": 10
                }, {
                    "name": "正确洗手的步骤",
                    "symbolSize": 10
                }, {
                    "name": "疑似病人的居家隔离",
                    "symbolSize": 10
                }, {
                    "name": "旅行中新冠病毒的预防",
                    "symbolSize": 10
                }, {
                    "name": "面对新冠肺炎\n的个人心理调节",
                    "symbolSize": 10
                }, {
                    "name": "农贸市场的预防传染",
                    "symbolSize": 10
                }, {
                    "name": "影剧院的预防传染",
                    "symbolSize": 10
                }, {
                    "name": "公共交通设施的预防传染",
                    "symbolSize": 10
                }, {
                    "name": "办公室的预防传染",
                    "symbolSize": 10
                }, {
                    "name": "医院的预防传染",
                    "symbolSize": 10
                }, {
                    "name": "医务人员个人防护",
                    "symbolSize": 10
                }, {
                    "name": "发热门诊的医务人员防护服",
                    "symbolSize": 10
                }, {
                    "name": "个人防护用品的配备",
                    "symbolSize": 10
                }, {
                    "name": "法定传染病和检疫传染病",
                    "symbolSize": 10
                }, {
                    "name": "传染病的防治方针和原则",
                    "symbolSize": 10
                }, {
                    "name": "新冠肺炎纳入乙类传染病\n按甲类管理",
                    "symbolSize": 10
                }, {
                    "name": "超级传播者",
                    "symbolSize": 10
                }, {
                    "name": "超级传播者的特点",
                    "symbolSize": 10
                }, {
                    "name": "‘毒王’",
                    "symbolSize": 10
                }, {
                    "name": "隔离医学观察",
                    "symbolSize": 10
                }, ]
            };
            let option = {
                animationDurationUpdate: 1500,
                animationEasingUpdate: 'quinticInOut',
                series: [{
                    name: "relation",
                    type: 'graph',
                    layout: 'circular',
                    circular: {
                        rotateLabel: true
                    },
                    data: graph.nodes.map(item => {
                        return {
                            id: item.id,
                            name: item.name,
                            symbolSize: item.symbolSize
                        }
                    }),
                    links: graph.links,
                    roam: true,
                    label: {
                        fontSize: 10,
                        show: true,
                        position: 'right',
                        formatter: '{b}',
                        interval: 0
                    },
                    itemStyle: {
                        color: "#4ad8c3"
                    },
                    emphasis: {
                        lineStyle: {
                            width: "3"
                        }
                    },
                    focusNodeAdjacency: true,
                    lineStyle: {
                        color: new echarts.graphic.LinearGradient(0, 0, 0, 1, [{
                            offset: 0,
                            color: '#4e8ebf'
                        }, {
                            offset: 0.45,
                            color: '#9ac8e0'
                        }, {
                            offset: 0.65,
                            color: '#ba3036'
                        }, {
                            offset: 1,
                            color: '#c84641'
                        }]),
                        curveness: 0.3
                    }
                }]
            };
            let myChart1 = echarts.init(document.getElementById('myChart1'));
            myChart1.setOption(option);
            console.log(1)
        }

    }
</script>
<style scoped>
    #myChart1 {
        position: absolute;
        height: 100%;
        width: 100%;
        left: 0;
        top: 0;
        background: var(--bg-darkColor);
    }
    
    .bg {
        position: absolute;
        width: 300px;
    }
</style>